export const planFeatures = [
  "teacher_profile",
  "marketplace_listing",
  "booking_calendar",
  "direct_messaging",
  "one_on_one_lessons",
  "basic_analytics",
  "community_support",
  "direct_payments",
  "courses",
  "homework",
  "file_sharing",
  "student_notes",
  "email_reminders",
  "reviews",
  "basic_reporting",
  "custom_availability",
  "unlimited_courses",
  "quizzes",
  "assignments",
  "certificates",
  "group_lessons",
  "calendar_sync",
  "video_integrations",
  "advanced_analytics",
  "priority_support",
  "team_teachers",
  "custom_branding",
  "api_access",
  "white_label_certificates",
  "advanced_reporting",
  "automation",
  "early_access",
] as const;

export type PlanFeature = (typeof planFeatures)[number];

export const planFeatureLabels: Record<string, string> = {
  teacher_profile: "Teacher profile",
  marketplace_listing: "Find Tutor & Courses listing",
  booking_calendar: "Booking calendar",
  direct_messaging: "Direct messaging",
  one_on_one_lessons: "One-on-one lessons",
  basic_analytics: "Basic analytics",
  community_support: "Community support",
  direct_payments: "Direct payment linking",
  courses: "Course creation & sales",
  homework: "Homework",
  file_sharing: "File sharing",
  student_notes: "Student notes",
  email_reminders: "Email reminders",
  reviews: "Reviews",
  basic_reporting: "Basic reporting",
  custom_availability: "Custom availability",
  unlimited_courses: "Unlimited courses · 0% commission",
  quizzes: "Quizzes",
  assignments: "Assignments",
  certificates: "Certificates",
  group_lessons: "Group lessons",
  calendar_sync: "Calendar sync",
  video_integrations: "HD video lessons",
  advanced_analytics: "Advanced analytics",
  priority_support: "Priority support",
  team_teachers: "Team teachers",
  custom_branding: "Custom branding",
  api_access: "API access (future)",
  white_label_certificates: "White-label certificates",
  advanced_reporting: "Advanced reporting",
  automation: "Automation",
  early_access: "Early access",
};
